services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped

  celery:
    build: .
    restart: unless-stopped
    command: celery -A config worker --loglevel=info --concurrency=4
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - db
      - redis

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=False
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
    volumes:
      - static_data:/app/static
      - media_data:/app/media

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8300:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/app/static:ro
      - media_data:/app/media:ro
    depends_on:
      - web

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password_123
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  static_data:
  media_data:
  minio_data:
