# Generated by Django 6.0.6 on 2026-06-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_manifest',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls/'),
        ),
    ]
